### PR TITLE
SCP-12: OrbitDB Address Formats and Class

### PR DESCRIPTION
**Pull request by tabcat**
[SCP-12.md](https://github.com/tabcat/SCPs/blob/SCP-11/scps/SCP-11.md)

### CODE REVIEW

**Comment by tabcat** [comment]
I kind of dislike the address class and wonder if just using CIDs would be fine.

**Comment by haadcode** [comment]
> I kind of dislike the address class and wonder if just using CIDs would be fine.

Agreed 👍

**Comment by CSDUMMI** [comment]
**Compatibility with `\`**
You don't seem to support the use of `\` instead of `/` in the string representation
of the addresses.

Is this intentional and should this behavior be removed or should compatibility with `\` be added to the SCP?

**Comment by tabcat** [comment]
good question, I'm not totally familiar with how or why these are used. good area to see what multiaddr does? i think they should be only `/orbitdb/<cid>` formatted strings, and they are when parsed currently, but needs more investigation.

**Comment by CSDUMMI** [comment]
I think they are used for compatibility with Windows, since the `ipfs` daemon provides an ability to mount `/ipfs` and `/ipns` dirs on Linux, making it possible to use commands like `cat /ipfs/Qm...` to work with IPFS files.

Maybe `\` are thus supported for the `/ipfs` and `/ipns` addresses to allow for the same functionality on Windows?

**Comment by tabcat** [comment]
I think it would be a good idea to use as few NodeJS apis, if any are even necessary. I don't think we need to support Windows paths everywhere to also support Windows users but maybe I'm wrong.

**Comment by CSDUMMI** [comment]
> I think it would be a good idea to use as few NodeJS apis, if any are even necessary. 

Why do we need to support NodeJS APIs?

**Comment by tabcat** [comment]
I'm talking about Node packages like 'path' and built in objects like Buffer. In other environments these have to be bundled with polyfills that can be large. Path is the relevant Node package in this case.

**Comment by CSDUMMI** [comment]
I don't think so. Currently the compatibility with Windows is achieved with `address.toString.replace`.

[https://github.com/orbitdb/orbit-db/blob/5df477ea27f23ad143cae80860767271618ca365/src/orbit-db-address.js#L18](https://github.com/orbitdb/orbit-db/blob/5df477ea27f23ad143cae80860767271618ca365/src/orbit-db-address.js#L18)

**Pull request closed without merging**
